### ISSUE TITLE
Не работает mouseenter

### ISSUE THREAD

**Issue by pfrlv** [monkberry/events#1]
Привет! Не работают события типа mouseenter, mouseleave и тд.
`this.on('mouseenter', 'a', (e) => {
      console.log( e.target );
    });`

**Comment by antonmedv** [comment]
А так?
```js
view.on('mouseenter', 'a', (e) => { console.log( e.target ); });
```

**Comment by antonmedv** [comment]
Либо попробуй это https://github.com/monkberry/directives

**Comment by pfrlv** [comment]
Хм.
`view` у меня в index, а это я хотел в конструкторе. Ну ладно, я сделаю через directives.

Спасибо!
